// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-materials.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/sheets.ts
async function readSheet(sheet) {
  const supabaseUrl = process.env.SUPABASE_URL;
  const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!supabaseUrl || !anonKey) {
    throw new Error("Supabase env not configured");
  }
  const res = await fetch(`${supabaseUrl}/functions/v1/google-sheets`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      apikey: anonKey,
      Authorization: `Bearer ${anonKey}`
    },
    body: JSON.stringify({ action: "read", sheet })
  });
  if (!res.ok) {
    throw new Error(`Failed to read ${sheet}: ${res.status}`);
  }
  const json = await res.json();
  if (!json?.success) {
    throw new Error(json?.error || `Failed to read ${sheet}`);
  }
  return json.data ?? [];
}
function toNumber(v) {
  const n = typeof v === "number" ? v : parseFloat(String(v ?? ""));
  return Number.isFinite(n) ? n : 0;
}

// src/lib/mcp/tools/list-materials.ts
var list_materials_default = defineTool({
  name: "list_materials",
  title: "List materials",
  description: "List all materials (\u0E27\u0E31\u0E2A\u0E14\u0E38) in the hospital inventory, including id, name, category, and unit. Optionally filter by a substring match on id or name.",
  inputSchema: {
    search: z.string().optional().describe("Optional substring to match against material id or name."),
    limit: z.number().int().positive().optional().describe("Maximum number of rows to return (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    const rows = await readSheet("products");
    const q = (search ?? "").toString().trim().toLowerCase();
    const filtered = q ? rows.filter(
      (r) => String(r.id ?? "").toLowerCase().includes(q) || String(r.name ?? "").toLowerCase().includes(q)
    ) : rows;
    const capped = filtered.slice(0, limit ?? 200);
    return {
      content: [{ type: "text", text: JSON.stringify(capped, null, 2) }],
      structuredContent: { count: capped.length, items: capped }
    };
  }
});

// src/lib/mcp/tools/get-stock-balance.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_stock_balance_default = defineTool2({
  name: "get_stock_balance",
  title: "Get stock balance",
  description: "Compute current stock balance for each material by aggregating all stock-in and stock-out transactions. Optionally filter by material id.",
  inputSchema: {
    material_id: z2.string().optional().describe("Optional material id (e.g. B1) to return balance for a single material.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ material_id }) => {
    const [products, ins, outs] = await Promise.all([
      readSheet("products"),
      readSheet("stock_in"),
      readSheet("stock_out")
    ]);
    const balances = /* @__PURE__ */ new Map();
    for (const r of ins) {
      const pid = String(r.product_id ?? "");
      if (!pid) continue;
      balances.set(pid, (balances.get(pid) ?? 0) + toNumber(r.quantity));
    }
    for (const r of outs) {
      const pid = String(r.product_id ?? "");
      if (!pid) continue;
      balances.set(pid, (balances.get(pid) ?? 0) - toNumber(r.quantity));
    }
    const items = products.map((p) => ({
      id: String(p.id ?? ""),
      name: String(p.name ?? ""),
      unit: String(p.unit ?? ""),
      balance: balances.get(String(p.id ?? "")) ?? 0
    })).filter((p) => material_id ? p.id === material_id : true);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function inRange(dateStr, from, to) {
  if (!from && !to) return true;
  const s = String(dateStr ?? "");
  if (from && s < from) return false;
  if (to && s > to) return false;
  return true;
}
var list_transactions_default = defineTool3({
  name: "list_transactions",
  title: "List stock transactions",
  description: "List stock-in (\u0E23\u0E31\u0E1A\u0E40\u0E02\u0E49\u0E32) or stock-out (\u0E40\u0E1A\u0E34\u0E01) transactions. Optionally filter by material id and by ISO date range (YYYY-MM-DD).",
  inputSchema: {
    type: z3.enum(["in", "out"]).describe("'in' for stock-in (\u0E23\u0E31\u0E1A\u0E40\u0E02\u0E49\u0E32), 'out' for stock-out (\u0E40\u0E1A\u0E34\u0E01)."),
    material_id: z3.string().optional().describe("Optional material id filter (e.g. B1)."),
    date_from: z3.string().optional().describe("Optional start date YYYY-MM-DD (inclusive)."),
    date_to: z3.string().optional().describe("Optional end date YYYY-MM-DD (inclusive)."),
    limit: z3.number().int().positive().optional().describe("Max rows to return (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, material_id, date_from, date_to, limit }) => {
    const sheet = type === "in" ? "stock_in" : "stock_out";
    const rows = await readSheet(sheet);
    const filtered = rows.filter((r) => {
      if (material_id && String(r.product_id ?? "") !== material_id) return false;
      if (!inRange(r.date, date_from, date_to)) return false;
      return true;
    });
    const capped = filtered.slice(0, limit ?? 200);
    return {
      content: [{ type: "text", text: JSON.stringify(capped, null, 2) }],
      structuredContent: { count: capped.length, items: capped }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "prachathipat-inventory-mcp",
  title: "\u0E23\u0E30\u0E1A\u0E1A\u0E27\u0E31\u0E2A\u0E14\u0E38\u0E04\u0E07\u0E04\u0E25\u0E31\u0E07 \u0E42\u0E23\u0E07\u0E1E\u0E22\u0E32\u0E1A\u0E32\u0E25\u0E1B\u0E23\u0E30\u0E0A\u0E32\u0E18\u0E34\u0E1B\u0E31\u0E15\u0E22\u0E4C (MCP)",
  version: "0.1.0",
  instructions: "Read-only tools for the Prachathipat Hospital material inventory system. Use list_materials to search the material catalog, get_stock_balance to compute current stock per material, and list_transactions to inspect stock-in (\u0E23\u0E31\u0E1A\u0E40\u0E02\u0E49\u0E32) or stock-out (\u0E40\u0E1A\u0E34\u0E01) history.",
  tools: [list_materials_default, get_stock_balance_default, list_transactions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
